### ISSUE TITLE
Active support?

### ISSUE THREAD

**Issue by classicyuppie** [sethlilly/Vapor#48]
With the last major revision of this repo being launched over a year ago, I have to ask if this is still an actively supported project, If it is, can we expect an update soon? I'm seeing deprecation notices when I test the theme on my local development version, asking that `pageUrl` be updated to `page_url`. Ghost stopped supporting this call syntax in version 0.6, and the production version of Ghost is now up to 0.7.

**Comment by sethlilly** [comment]
Hi @classicyuppie! I just [updated the roadmap](https://github.com/sethlilly/Vapor/wiki/Roadmap) with information about the next release. I'm going to nail down a release date this week and will publish ASAP. I've been neglecting this project too long and just need to take some time and get it out there. Thanks for your continued support!

**Comment by classicyuppie** [comment]
Glad to see further development is planned. I looked at the roadmap and will continue to support the Vapor theme any way I can.
