### ISSUE TITLE
Change in display font

### ISSUE THREAD

**Issue by classicyuppie** [sethlilly/Vapor#50]
Is anyone else seeing a change in the font used to display the content? I checked my blog randomly this morning and found that the font-face had changed to what looks like Open Sans? Did something happen with the primary Merriweather font in the CSS?

```
h1,
h2,
h3,
h4,
p,
li,
dt,
dd {
  font-family: "Merriweather", "Open Sans", "Helvetica Neue", Helvetica, Arial, "Nimbus L", sans-serif;
}
```

**Comment by sethlilly** [comment]
@classicyuppie Your blog looks good here. I'm seeing Merriweather where it should be. Open Sans is the fallback so it's possible there was a temporary issue with Merriweather. Leaving this issue open until I hear back from you.

**Comment by classicyuppie** [comment]
Odd. I'm not seeing it still. Attaching a screen cap below:

![screen shot 2015-10-23 at 11 24 08 am](https://cloud.githubusercontent.com/assets/3246415/10697187/ae4502a4-7978-11e5-80ee-6a11da684a43.png)

**Comment by sethlilly** [comment]
Thanks for the screencap, John. I'll check it out.

**Comment by classicyuppie** [comment]
So weird. I just checked on it a little bit ago and it's fine now...

<img width="1545" alt="screen shot 2015-10-23 at 9 31 07 pm" src="https://cloud.githubusercontent.com/assets/3246415/10708184/6d182bd0-79cd-11e5-9a20-b39df3fffd87.png">

IDK what happened, but I think I can close this one out.
