### ISSUE TITLE
The formatting of post previews on index page does not match the formatting of post on permalink page

### ISSUE THREAD

**Issue by dougmckown** [sethlilly/Vapor#51]
When you view the blog index page, the formatting of the text in the post previews does not match the formatting in a post when viewed as a permalink. 

Index page: 
<img width="632" alt="screen shot 2015-10-25 at 1 25 18 am" src="https://cloud.githubusercontent.com/assets/1332160/10714186/ff44d162-7ab7-11e5-80c5-c72b63c4af2a.png">

Individual/permalink post: <img width="634" alt="screen shot 2015-10-25 at 1 25 05 am" src="https://cloud.githubusercontent.com/assets/1332160/10714184/cce08a18-7ab7-11e5-9223-106ce724ecaf.png">

**Comment by dougmckown** [comment]
My apologies: I now realize it's {{excerpt}} vs. {{content}}.

**Comment by sethlilly** [comment]
No worries! Thanks for reporting, @dougmckown.
