### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by wimel** [sethlilly/Vapor#68]
I think it might be silly :sweat_smile:, but I think it would be nice to put the steps to start using it in the README, I think it can help more people use it.
If you think it's a good option I can try to make it the best I can

**Comment by pascalandy** [comment]
I'm not sure what you mean here? The steps to import a theme into Ghost ?

**Comment by wimel** [comment]
Sorry was a mistake on my behalf. Sorry for the inconvenience.
